# Generated by Django 4.0 on 2021-12-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('narx', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=20)),
                ('familiya', models.CharField(max_length=20)),
                ('sharif', models.CharField(blank=True, max_length=20, null=True)),
                ('jins', models.CharField(choices=[("o'g'il", "o'g'il"), ('qiz', 'qiz')], max_length=12)),
                ('tel1', models.CharField(max_length=13)),
                ('tel2', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Ustoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('familiya', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Shartnoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_raqami', models.SmallIntegerField()),
                ('sinov_dars_sanasi', models.DateField()),
                ('kunlar', models.CharField(choices=[('Dushanba-Juma', 'Dushanba-Juma'), ('Seshanba-Shanba', 'Seshanba-Shanba')], max_length=30)),
                ('vaqt', models.CharField(choices=[('08:00-10:00', '08:00-10:00'), ('10:00-12:00', '10:00-12:00'), ('14:00-16:00', '14:00-16:00'), ('16:00-18:00', '16:00-18:00'), ('18:00-20:00', '18:00-20:00')], max_length=20)),
                ('guruh_nomi', models.CharField(max_length=15)),
                ('student_holati', models.CharField(choices=[('yangi', 'yangi'), ('loyal', 'loyal')], max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Passive', 'Passive')], max_length=10)),
                ('tuzuvchi', models.CharField(max_length=15)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shartnoma.kurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shartnoma.student')),
                ('ustoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shartnoma.ustoz')),
            ],
        ),
    ]
